/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package conversor_doble;

import javax.swing.JOptionPane;

/**
 *
 * @author Jox
 */
public class Converso_Money extends javax.swing.JFrame {

    /**
     * Creates new form Converso_Money
     */
    public Converso_Money() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtImporte = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbnLista1 = new javax.swing.JComboBox<>();
        jbnLista2 = new javax.swing.JComboBox<>();
        btnConvertir = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        txtResul = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Convertidor de Moneda");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 320, 40));

        txtImporte.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        getContentPane().add(txtImporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 102, -1));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("A: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Convertir De:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        jbnLista1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbnLista1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Soles", "Dolar", "Euro", "Libra Esterlina", "Yen Japones", "Peso Mexicano", "Real Brasilero" }));
        jbnLista1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnLista1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbnLista1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 102, -1));

        jbnLista2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbnLista2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Soles", "Dolar", "Euro", "Libra Esterlina", "Yen Japones", "Peso Mexicano", "Real Brasilero" }));
        getContentPane().add(jbnLista2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 106, -1));

        btnConvertir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnConvertir.setText("Convertir");
        btnConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirActionPerformed(evt);
            }
        });
        getContentPane().add(btnConvertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 90, 30));

        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/atras.png"))); // NOI18N
        btnAtras.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 40, 40));

        txtResul.setEditable(false);
        txtResul.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        txtResul.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtResul, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 100, 30));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Importe:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Resultado:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/money.png"))); // NOI18N
        jLabel6.setToolTipText("");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 50, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondo.PNG"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
     this.setVisible(false);
     Vist_Inicio v = new Vist_Inicio();
     v.setVisible(true);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed
        
        
        try {
            int indice1 =jbnLista1.getSelectedIndex();
            int indice2= jbnLista2.getSelectedIndex();
            double impor =Double.parseDouble(txtImporte.getText());
            Convertir_money c = new Convertir_money(impor,indice1,indice2);
            double resul = Math.round(c.Conversion_dinero()*1000.0)/1000.0;
            txtResul.setText(String.valueOf(resul));
        } catch (NumberFormatException e) {
            //e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ingrese una cantida validad");
            txtImporte.setText("");
        } catch (AssertionError ex) {
            JOptionPane.showMessageDialog(null,"Escoga el tipo de cambio");
        }
    }//GEN-LAST:event_btnConvertirActionPerformed

    private void jbnLista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnLista1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbnLista1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Converso_Money.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Converso_Money.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Converso_Money.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Converso_Money.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Converso_Money().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnConvertir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> jbnLista1;
    private javax.swing.JComboBox<String> jbnLista2;
    private javax.swing.JTextField txtImporte;
    private javax.swing.JTextField txtResul;
    // End of variables declaration//GEN-END:variables
}
